# Midgut hPTM differential covariance analysis

# Libraries
library(Hmisc)
library(vegan)
library(corrplot)
library(dplyr)
library(ggplot2)
library(readr)

# Settings
INPUT_RDS <- "05_batch_correction_limma/H3_H4_5PTM_midgut_batch_corrected_limma.rds"
METADATA_FILE <- "STPN2309_metadata_all.tsv"

# Correlation matrices generated by 08_a_covariance analysis_corr
CORR_DIR <- "08_a_covariance analysis_corr"

OUTPUT_DIR <- "08_b_differential_covariance_analysis"
dir.create(OUTPUT_DIR, showWarnings = FALSE, recursive = TRUE)

SAMPLE_ID_COL <- "sampleID_STPN2309"
DIET_COL <- "diet"

GROUP_A <- "NC"
GROUP_B <- "HC"
DIETS_TO_KEEP <- c(GROUP_A, GROUP_B)

N_PERM <- 10000
SEED <- 123

BASE_SIZE <- 14
TITLE_FAMILY <- "mono"
TITLE_SIZE <- 16

cols2diet <- c(
  "NC" = "#44a7c4",
  "HC" = "#f99943"
)

# Helper functions
pairwise_cor_matrix <- function(df, method = "spearman") {
  res <- rcorr(as.matrix(df), type = method)
  list(r = res$r, P = res$P, n = res$n)
}

upper_tri_vec <- function(mat) {
  mat[upper.tri(mat)]
}

vector_to_symmetric_matrix <- function(vec, feature_names, diag_value = 0) {
  p <- length(feature_names)

  mat <- matrix(
    NA_real_,
    nrow = p,
    ncol = p,
    dimnames = list(feature_names, feature_names)
  )

  mat[upper.tri(mat)] <- vec
  mat[lower.tri(mat)] <- t(mat)[lower.tri(mat)]
  diag(mat) <- diag_value

  mat
}

safe_iqr <- function(x) {
  x <- x[!is.na(x)]

  if (length(x) < 2) {
    return(NA_real_)
  }

  IQR(x)
}

theme_cutler <- function() {
  theme_bw(base_size = BASE_SIZE) +
    theme(
      panel.grid = element_blank(),
      axis.text = element_text(color = "black"),
      axis.title = element_text(face = "bold"),
      plot.title = element_text(
        family = TITLE_FAMILY,
        size = TITLE_SIZE,
        face = "bold"
      ),
      plot.title.position = "plot",
      plot.margin = margin(t = 10, r = 5, b = 5, l = 5)
    )
}

p_to_symbol <- function(p) {
  if (is.na(p)) return("NA")
  if (p <= 1e-4) return("****")
  if (p <= 1e-3) return("***")
  if (p <= 1e-2) return("**")
  if (p <= 0.05) return("*")
  "ns"
}

read_matrix_tsv <- function(path) {
  if (!file.exists(path)) {
    stop("File not found: ", path)
  }

  as.matrix(
    read.table(
      path,
      header = TRUE,
      row.names = 1,
      sep = "\t",
      check.names = FALSE,
      quote = "",
      comment.char = ""
    )
  )
}

# Check input files
if (!file.exists(INPUT_RDS)) {
  stop("Corrected hPTM RDS not found: ", INPUT_RDS)
}

if (!file.exists(METADATA_FILE)) {
  stop("Metadata TSV not found: ", METADATA_FILE)
}

# Load limma-corrected hPTM matrix and metadata
cat("Loading limma-corrected hPTM matrix and metadata...\n")

rds_obj <- readRDS(INPUT_RDS)

if (!"ptm_batch_corrected_limma" %in% names(rds_obj)) {
  stop(
    "Object 'ptm_batch_corrected_limma' not found in: ",
    INPUT_RDS
  )
}

ptm_df <- as.data.frame(
  rds_obj$ptm_batch_corrected_limma,
  stringsAsFactors = FALSE
)

meta_df <- read.delim(
  METADATA_FILE,
  sep = "\t",
  header = TRUE,
  stringsAsFactors = FALSE,
  check.names = FALSE
)

if (is.null(rownames(ptm_df))) {
  stop("Corrected hPTM matrix must contain sample IDs as rownames.")
}

required_cols <- c(SAMPLE_ID_COL, DIET_COL)
missing_cols <- setdiff(required_cols, names(meta_df))

if (length(missing_cols) > 0) {
  stop(
    "Missing metadata column(s): ",
    paste(missing_cols, collapse = ", ")
  )
}

# Align corrected matrix and metadata
rownames(ptm_df) <- trimws(rownames(ptm_df))

meta_df[[SAMPLE_ID_COL]] <- trimws(
  as.character(meta_df[[SAMPLE_ID_COL]])
)

meta_df[[DIET_COL]] <- trimws(
  as.character(meta_df[[DIET_COL]])
)

if (anyDuplicated(rownames(ptm_df)) > 0) {
  stop("Duplicated sample IDs found in corrected hPTM matrix.")
}

if (anyDuplicated(meta_df[[SAMPLE_ID_COL]]) > 0) {
  stop("Duplicated sample IDs found in metadata.")
}

# Standardize hPTM names: H4K16Ac -> H4K16ac
# Combined marks are handled separately: H3K36La|H3K37La
normalize_ptm <- function(x) {
  vapply(
    x,
    function(entry) {
      parts <- strsplit(entry, "\\|")[[1]]
      
      norm_parts <- vapply(
        parts,
        function(p) {
          g <- regmatches(
            p,
            regexec(
              "^(H[34])(K|R)([0-9]{1,3})([A-Za-z0-9]+)$",
              p
            )
          )[[1]]
          
          if (length(g) < 5 || is.na(g[1])) {
            return(NA_character_)
          }
          
          paste0(g[2], g[3], g[4], tolower(g[5]))
        },
        character(1)
      )
      
      if (any(is.na(norm_parts))) {
        return(NA_character_)
      }
      
      paste(norm_parts, collapse = "|")
    },
    character(1),
    USE.NAMES = FALSE
  )
}

normalized_names <- normalize_ptm(colnames(ptm_df))

if (anyNA(normalized_names)) {
  stop(
    "Could not normalize PTM name(s): ",
    paste(colnames(ptm_df)[is.na(normalized_names)], collapse = ", ")
  )
}

if (anyDuplicated(normalized_names) > 0) {
  stop("Duplicated PTM names produced after lowercase normalization.")
}

colnames(ptm_df) <- normalized_names


meta_df <- meta_df[
  meta_df[[DIET_COL]] %in% DIETS_TO_KEEP,
  ,
  drop = FALSE
]

common_ids <- rownames(ptm_df)[
  rownames(ptm_df) %in% meta_df[[SAMPLE_ID_COL]]
]

if (length(common_ids) == 0) {
  stop("No matching sample IDs found between corrected hPTM matrix and metadata.")
}

ptm_df <- ptm_df[common_ids, , drop = FALSE]

meta_df <- meta_df[
  match(common_ids, meta_df[[SAMPLE_ID_COL]]),
  ,
  drop = FALSE
]

rownames(meta_df) <- meta_df[[SAMPLE_ID_COL]]

stopifnot(identical(rownames(ptm_df), rownames(meta_df)))

meta_df[[DIET_COL]] <- factor(
  meta_df[[DIET_COL]],
  levels = c(GROUP_A, GROUP_B)
)

ptm_df[] <- lapply(
  ptm_df,
  function(x) suppressWarnings(as.numeric(x))
)

if (anyDuplicated(colnames(ptm_df)) > 0) {
  stop("Duplicated PTM names found in corrected hPTM matrix.")
}

idx_A <- which(meta_df[[DIET_COL]] == GROUP_A)
idx_B <- which(meta_df[[DIET_COL]] == GROUP_B)

if (length(idx_A) < 4 || length(idx_B) < 4) {
  stop("Need at least 4 samples per diet group.")
}

ptm_A_full <- ptm_df[idx_A, , drop = FALSE]
ptm_B_full <- ptm_df[idx_B, , drop = FALSE]

cat("Aligned corrected data:\n")
cat("PTM matrix:", nrow(ptm_df), "samples x", ncol(ptm_df), "PTMs\n")
cat(GROUP_A, "samples:", nrow(ptm_A_full), "\n")
cat(GROUP_B, "samples:", nrow(ptm_B_full), "\n\n")

# Load correlation matrices from the preceding covariance analysis
cat("Loading NC and HC correlation matrices...\n")

cor_A <- read_matrix_tsv(
  file.path(CORR_DIR, GROUP_A, paste0("spearman_correlation_matrix_", GROUP_A, ".tsv"))
)

cor_B <- read_matrix_tsv(
  file.path(CORR_DIR, GROUP_B, paste0("spearman_correlation_matrix_", GROUP_B, ".tsv"))
)

n_A_matrix <- read_matrix_tsv(
  file.path(CORR_DIR, GROUP_A, paste0("spearman_pairwise_n_matrix_", GROUP_A, ".tsv"))
)

n_B_matrix <- read_matrix_tsv(
  file.path(CORR_DIR, GROUP_B, paste0("spearman_pairwise_n_matrix_", GROUP_B, ".tsv"))
)

common_features <- Reduce(
  intersect,
  list(
    rownames(cor_A),
    colnames(cor_A),
    rownames(cor_B),
    colnames(cor_B),
    rownames(n_A_matrix),
    colnames(n_A_matrix),
    rownames(n_B_matrix),
    colnames(n_B_matrix),
    colnames(ptm_df)
  )
)

if (length(common_features) < 2) {
  stop("Fewer than 2 common hPTMs between corrected data and correlation matrices.")
}

cor_A <- cor_A[common_features, common_features, drop = FALSE]
cor_B <- cor_B[common_features, common_features, drop = FALSE]
n_A_matrix <- n_A_matrix[common_features, common_features, drop = FALSE]
n_B_matrix <- n_B_matrix[common_features, common_features, drop = FALSE]

ptm_A <- ptm_A_full[, common_features, drop = FALSE]
ptm_B <- ptm_B_full[, common_features, drop = FALSE]
ptm_all <- ptm_df[c(idx_A, idx_B), common_features, drop = FALSE]

cat("Common hPTMs:", length(common_features), "\n\n")

# hPTM variability
cat("hPTM variability analysis...\n")

iqr_A <- vapply(ptm_A, safe_iqr, numeric(1))
iqr_B <- vapply(ptm_B, safe_iqr, numeric(1))

iqr_df <- data.frame(
  iqr = c(iqr_A, iqr_B),
  group = factor(
    c(
      rep(GROUP_A, length(iqr_A)),
      rep(GROUP_B, length(iqr_B))
    ),
    levels = c(GROUP_A, GROUP_B)
  ),
  feature = c(names(iqr_A), names(iqr_B))
) %>%
  filter(!is.na(iqr), is.finite(iqr))

wilcox_iqr <- wilcox.test(iqr ~ group, data = iqr_df)

iqr_summary <- data.frame(
  test = "Wilcoxon rank-sum",
  n_features_per_group = length(iqr_A),
  median_NC = median(iqr_A, na.rm = TRUE),
  median_HC = median(iqr_B, na.rm = TRUE),
  W = unname(wilcox_iqr$statistic),
  p_value = wilcox_iqr$p.value,
  significant = wilcox_iqr$p.value < 0.05
)

write.csv(
  iqr_summary,
  file.path(OUTPUT_DIR, "hPTM_variability_IQR_summary.csv"),
  row.names = FALSE
)

iqr_label <- p_to_symbol(wilcox_iqr$p.value)
ymax_B <- max(iqr_df$iqr, na.rm = TRUE)

pB <- ggplot(iqr_df, aes(x = group, y = iqr, fill = group)) +
  geom_violin(trim = FALSE, color = "black", width = 0.9) +
  geom_boxplot(width = 0.14, outlier.shape = NA, fill = "white") +
  stat_summary(fun = median, geom = "point", shape = 95, size = 5, color = "black") +
  annotate(
    "text",
    x = 1.5,
    y = ymax_B * 1.05,
    label = iqr_label,
    size = 6,
    fontface = "bold"
  ) +
  scale_fill_manual(values = cols2diet) +
  coord_cartesian(
    ylim = c(min(iqr_df$iqr, na.rm = TRUE), ymax_B * 1.12)
  ) +
  labs(
    x = "",
    y = "Interquartile Range (IQR)"
    #title = "Midgut hPTMs variability"
  ) +
  theme_cutler() +
  theme(legend.position = "none")

ggsave(
  file.path(OUTPUT_DIR, "hPTM_variability_IQR.pdf"),
  pB,
  width = 4.5,
  height = 4
)

ggsave(
  file.path(OUTPUT_DIR, "hPTM_variability_IQR.tiff"),
  pB,
  width = 4.5,
  height = 4,
  dpi = 800,
  compression = "lzw"
)

# Mantel comparison
cat("Mantel comparison of NC and HC correlation matrices...\n")

cor_A_mantel <- cor_A
cor_B_mantel <- cor_B

cor_A_mantel[is.na(cor_A_mantel)] <- 0
cor_B_mantel[is.na(cor_B_mantel)] <- 0

set.seed(SEED)

mantel_res <- mantel(
  cor_A_mantel,
  cor_B_mantel,
  permutations = N_PERM
)

mantel_summary <- data.frame(
  test = "Mantel",
  statistic_r = unname(mantel_res$statistic),
  p_value = mantel_res$signif,
  permutations = N_PERM,
  significant = mantel_res$signif < 0.05
)

write.csv(
  mantel_summary,
  file.path(OUTPUT_DIR, "correlation_structure_Mantel_NC_vs_HC.csv"),
  row.names = FALSE
)

# Distribution of differential correlations
cat("Differential correlation distribution...\n")

cor_A[cor_A > 1] <- 1
cor_A[cor_A < -1] <- -1
cor_B[cor_B > 1] <- 1
cor_B[cor_B < -1] <- -1

log2FC_mat <- log2((cor_B + 1) / (cor_A + 1))
diag(log2FC_mat) <- 0

log2FC_vec <- upper_tri_vec(log2FC_mat)

log2FC_df <- data.frame(log2FC = log2FC_vec) %>%
  filter(!is.na(log2FC), is.finite(log2FC))

# Two-sided test for any global shift away from zero
ttest_shift <- t.test(
  log2FC_df$log2FC,
  mu = 0,
  alternative = "two.sided"
)


log2FC_stats <- data.frame(
  n_edges = nrow(log2FC_df),
  mean_log2FC = mean(log2FC_df$log2FC, na.rm = TRUE),
  median_log2FC = median(log2FC_df$log2FC, na.rm = TRUE),
  sd_log2FC = sd(log2FC_df$log2FC, na.rm = TRUE),
  min_log2FC = min(log2FC_df$log2FC, na.rm = TRUE),
  max_log2FC = max(log2FC_df$log2FC, na.rm = TRUE),
  t_statistic = unname(ttest_shift$statistic),
  df = unname(ttest_shift$parameter),
  p_value = ttest_shift$p.value,
  conf_low = ttest_shift$conf.int[1],
  conf_high = ttest_shift$conf.int[2],
  significant = ttest_shift$p.value < 0.05,
  direction = ifelse(
    mean(log2FC_df$log2FC, na.rm = TRUE) > 0,
    "positive_shift_HC_stronger",
    "negative_or_no_shift"
  )
)

write.csv(
  log2FC_stats,
  file.path(OUTPUT_DIR, "differential_correlation_distribution_summary.csv"),
  row.names = FALSE
)

dens_C <- density(log2FC_df$log2FC, na.rm = TRUE)
dens_df <- data.frame(x = dens_C$x, y = dens_C$y)

pC_subtitle <- paste0(
  "two-sided t-test: t = ",
  round(unname(ttest_shift$statistic), 2),
  ", df = ",
  round(unname(ttest_shift$parameter), 1),
  ", p = ",
  signif(ttest_shift$p.value, 3)
)

pC <- ggplot(dens_df, aes(x = x, y = y)) +
  geom_line(linewidth = 1, color = "black") +
  geom_vline(xintercept = 0, linetype = 2, color = "red") +
  annotate(
    "text",
    x = min(dens_df$x) * 0.6,
    y = max(dens_df$y) * 0.95,
    label = "Decreased in HC\nrelative to NC",
    hjust = 0.5,
    vjust = 1,
    fontface = "bold",
    size = 4
  ) +
  annotate(
    "text",
    x = max(dens_df$x) * 0.6,
    y = max(dens_df$y) * 0.95,
    label = "Increased in HC\nrelative to NC",
    hjust = 0.5,
    vjust = 1,
    fontface = "bold",
    size = 4
  ) +
  labs(
    x = expression(log[2] * "[(rho"[HC] * " + 1)/(rho"[NC] * " + 1)]"),
    y = "Density",
    #title = "Midgut hPTMs differential correlations\nHC vs NC",
    subtitle = pC_subtitle
  ) +
  theme_cutler()

mean_log2FC <- mean(log2FC_df$log2FC, na.rm = TRUE)

pC <- pC +
  geom_vline(
    xintercept = mean_log2FC,
    linetype = "solid",
    linewidth = 0.7
  )

ggsave(
  file.path(OUTPUT_DIR, "differential_correlation_distribution.pdf"),
  pC,
  width = 5,
  height = 4
)

ggsave(
  file.path(OUTPUT_DIR, "differential_correlation_distribution.tiff"),
  pC,
  width = 5,
  height = 4,
  dpi = 800,
  compression = "lzw"
)

# Differential-correlation permutation analysis
cat("Permutation test for differential correlations...\n")

set.seed(SEED)

n_all <- nrow(ptm_all)
n_samples_NC <- nrow(ptm_A)
n_samples_HC <- nrow(ptm_B)

feature_names <- common_features
obs_fc_vec <- upper_tri_vec(log2FC_mat)
n_pairs <- length(obs_fc_vec)

perm_fc_mat <- matrix(
  NA_real_,
  nrow = N_PERM,
  ncol = n_pairs
)

for (perm in seq_len(N_PERM)) {

  perm_idx <- sample(seq_len(n_all))

  grpA_idx <- perm_idx[seq_len(n_samples_NC)]

  grpB_idx <- perm_idx[
    (n_samples_NC + 1):(n_samples_NC + n_samples_HC)
  ]

  perm_A <- ptm_all[grpA_idx, , drop = FALSE]
  perm_B <- ptm_all[grpB_idx, , drop = FALSE]

  perm_cor_A <- pairwise_cor_matrix(
    perm_A,
    method = "spearman"
  )$r

  perm_cor_B <- pairwise_cor_matrix(
    perm_B,
    method = "spearman"
  )$r

  perm_cor_A <- perm_cor_A[
    feature_names,
    feature_names,
    drop = FALSE
  ]

  perm_cor_B <- perm_cor_B[
    feature_names,
    feature_names,
    drop = FALSE
  ]

  perm_cor_A[perm_cor_A > 1] <- 1
  perm_cor_A[perm_cor_A < -1] <- -1
  perm_cor_B[perm_cor_B > 1] <- 1
  perm_cor_B[perm_cor_B < -1] <- -1

  perm_fc <- log2(
    (perm_cor_B + 1) / (perm_cor_A + 1)
  )

  diag(perm_fc) <- 0

  perm_fc_mat[perm, ] <- upper_tri_vec(perm_fc)

  if (perm %% 100 == 0 || perm == N_PERM) {
    cat("Permutation", perm, "of", N_PERM, "\n")
  }
}

perm_p_vec <- rep(NA_real_, n_pairs)

for (j in seq_len(n_pairs)) {
  
  perm_vals <- perm_fc_mat[, j]
  
  valid <- is.finite(perm_vals)
  
  if (all(!valid) || !is.finite(obs_fc_vec[j])) {
    
    perm_p_vec[j] <- NA_real_
    
  } else {
    
    extreme_high <- (
      sum(perm_vals[valid] >= obs_fc_vec[j]) + 1
    ) / (
      sum(valid) + 1
    )
    
    extreme_low <- (
      sum(perm_vals[valid] <= obs_fc_vec[j]) + 1
    ) / (
      sum(valid) + 1
    )
    
    perm_p_vec[j] <- min(
      2 * min(extreme_high, extreme_low),
      1
    )
  }
}

padj_vec <- p.adjust(perm_p_vec, method = "BH")

perm_p_mat <- vector_to_symmetric_matrix(
  perm_p_vec,
  feature_names,
  diag_value = 0
)

padj_mat <- vector_to_symmetric_matrix(
  padj_vec,
  feature_names,
  diag_value = 0
)

res_list <- vector("list", n_pairs)
k <- 1

for (i in seq_len(length(feature_names) - 1)) {

  for (j in (i + 1):length(feature_names)) {

    f1 <- feature_names[i]
    f2 <- feature_names[j]

    res_list[[k]] <- data.frame(
      PTM_1 = f1,
      PTM_2 = f2,
      rho_NC = cor_A[f1, f2],
      rho_HC = cor_B[f1, f2],
      n_NC = n_A_matrix[f1, f2],
      n_HC = n_B_matrix[f1, f2],
      delta_rho = cor_B[f1, f2] - cor_A[f1, f2],
      log2FC_rho_plus_1 = log2FC_mat[f1, f2],
      permutation_p = perm_p_mat[f1, f2],
      BH_FDR = padj_mat[f1, f2],
      sign_change = sign(cor_A[f1, f2]) != sign(cor_B[f1, f2]),
      stringsAsFactors = FALSE
    )

    k <- k + 1
  }
}

pair_results <- bind_rows(res_list) %>%
  arrange(BH_FDR, permutation_p, desc(abs(log2FC_rho_plus_1)))

write.table(
  pair_results,
  file = file.path(
    OUTPUT_DIR,
    "differential_correlation_pairs.tsv"
  ),
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

permutation_summary <- data.frame(
  tested_pairs = nrow(pair_results),
  raw_p_below_0_05 = sum(pair_results$permutation_p < 0.05, na.rm = TRUE),
  BH_FDR_below_0_05 = sum(pair_results$BH_FDR < 0.05, na.rm = TRUE),
  BH_FDR_below_0_10 = sum(pair_results$BH_FDR < 0.10, na.rm = TRUE),
  permutations = N_PERM
)

write.csv(
  permutation_summary,
  file.path(
    OUTPUT_DIR,
    "differential_correlation_permutation_summary.csv"
  ),
  row.names = FALSE
)

# ------------------------------------------------------------------
# Significant-only matrix: BH-FDR < 0.05
# Blank labelled matrix if no pair survives correction
# ------------------------------------------------------------------

sig_mask_mat <- log2FC_mat
sig_mask_mat[padj_mat >= 0.05 | is.na(padj_mat)] <- NA
diag(sig_mask_mat) <- 0

n_sig_pairs <- sum(pair_results$BH_FDR < 0.05, na.rm = TRUE)

message("Significant differential-correlation pairs at BH-FDR < 0.05: ", n_sig_pairs)

plot_sig_corrplot <- function(filename, device = c("pdf", "tiff")) {
  
  device <- match.arg(device)
  
  if (device == "pdf") {
    pdf(filename, width = 6.5, height = 6.5)
  } else {
    tiff(
      filename = filename,
      width = 6.5,
      height = 6.5,
      units = "in",
      res = 1200,
      compression = "lzw"
    )
  }
  
  if (n_sig_pairs == 0) {
    
    suppressWarnings(
      corrplot(
        sig_mask_mat,
        is.corr = FALSE,
        method = "square",
        type = "lower",
        diag = TRUE,
        tl.pos = "ld",
        na.label = " ",
        col = colorRampPalette(c("white", "white"))(2),
        col.lim = c(-1, 1),
        tl.col = "black",
        tl.cex = 0.7,
        cl.pos = "n",
        title = "",
        mar = c(0, 0, 0, 2)
      )
    )
    
  } else {
    
    sig_vals <- sig_mask_mat[lower.tri(sig_mask_mat)]
    sig_vals <- sig_vals[is.finite(sig_vals)]
    
    max_abs_sig <- max(abs(sig_vals), na.rm = TRUE)
    
    corrplot(
      sig_mask_mat,
      is.corr = FALSE,
      method = "square",
      type = "lower",
      diag = FALSE,
      tl.pos = "ld",
      na.label = " ",
      col = colorRampPalette(c("#2166AC", "white", "#B2182B"))(200),
      col.lim = c(-max_abs_sig, max_abs_sig),
      tl.col = "black",
      tl.cex = 0.7,
      cl.pos = "r",
      cl.cex = 0.8,
      title = "",
      mar = c(0, 0, 0, 2)
    )
  }
  
  dev.off()
}

plot_sig_corrplot(
  file.path(OUTPUT_DIR, "significant_differential_correlation_matrix.pdf"),
  device = "pdf"
)

plot_sig_corrplot(
  file.path(OUTPUT_DIR, "significant_differential_correlation_matrix.tiff"),
  device = "tiff"
)


writeLines(
  capture.output(sessionInfo()),
  con = file.path(OUTPUT_DIR, "sessionInfo.txt")
)

cat("\nDone. Outputs saved in:", OUTPUT_DIR, "\n")

pairs <- read_tsv(
  "08_b_differential_covariance_analysis/differential_correlation_pairs.tsv",
  show_col_types = FALSE
)

sig_pairs <- pairs %>%
  filter(BH_FDR < 0.05) %>%
  arrange(BH_FDR, permutation_p, desc(abs(delta_rho)))

sig_pairs

# Save significant differential-correlation pairs only
write_csv(
  sig_pairs,
  "08_b_differential_covariance_analysis/significant_differential_correlation_pairs.csv"
)

